@baseUrl= http://localhost:3000

# Get all recados
GET {{baseUrl}}/recados
?limit=10
&offset=120

###
# Get a specific recado by ID
GET {{baseUrl}}/recados/2

###
# Create a new recado
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "recado": "This is a new recado",
    "nova chave": "another value"
}

###
# update a new recado
PATCH  {{baseUrl}}/recados/1/
Content-Type: application/json

{
    "recado": "This is a new recado",
    "nova chave": "another value"
}

###
# delete recado
DELETE  {{baseUrl}}/recados/1/

