@baseUrl= http://localhost:3002

# Get all recados
GET {{baseUrl}}/recados
?limit=10
&offset=120

###
# Get a specific recado by ID
GET {{baseUrl}}/recados/25

###
# Create a new recado
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "This is a new recado",
    "de": "Roberto",
    "para": "Cristina"
}

###
# update a new recado
PATCH  {{baseUrl}}/recados/25
Content-Type: application/json

{
    "texto": "This is a new update with prisma 2"
    
}

###
# delete recado
DELETE  {{baseUrl}}/recados/25/

