@baseUrl= http://localhost:3002
### Get all pessoas
GET {{baseUrl}}/pessoa

###
# Get a specific pessoa by ID
GET {{baseUrl}}/pessoa/1

### Create a new pessoa
POST {{baseUrl}}/pessoa
Content-Type: application/json

{
  "nome": "Roberto Oliveira",
  "senha": "14",
  "email": "roberto.oliveira@example.com"
}   

### Update 
PATCH  {{baseUrl}}/pessoa/1
Content-Type: application/json

{
  "nome": "Roberto Oliveira",
  "senha": "12",
  "email": "roberto.oliveira@example.com"
}   

### Delete a pessoa by ID
DELETE {{baseUrl}}/pessoa/4
