@baseUrl= http://localhost:3002

# Get all recados
GET {{baseUrl}}/recados
?limit=10
&offset=120

###
# Get a specific recado by ID
GET {{baseUrl}}/recados/2

###
# Create a new recado
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "This is a new recado",
    "deId": 3,
    "paraId": 1
}

###
# update a new recado
PATCH  {{baseUrl}}/recados/1
Content-Type: application/json

{
    "texto": "This is a new update with prisma 2",
    "deId": 1,
    "paraId": 3
    
}

###
# delete recado
DELETE  {{baseUrl}}/recados/3/

